### list genders
GET http://localhost:3000/genders

### get gender
GET http://localhost:3000/genders/y4QzJx0VC3Fv0JZpKkOwC

### create gender
POST http://localhost:3000/genders
Content-Type: application/json

{
  "name": "Terror"
}

### update gender
PATCH http://localhost:3000/genders/y4QzJx0VC3Fv0JZpKkOwC
Content-Type: application/json

{
  "name": "Comédia"
}

### delete gender
DELETE http://localhost:3000/genders/y4QzJx0VC3Fv0JZpKkOwC
