### list genres
GET http://localhost:3000/genders

### get gender
GET http://localhost:3000/genders/HjnJoL9dX0pcbLzft3xTk

### create gender
POST http://localhost:3000/genders
Content-Type: application/json

{
  "name": "Comédia"
}

### update gender
PATCH http://localhost:3000/genders/HjnJoL9dX0pcbLzft3xTk
Content-Type: application/json

{
  "name": "Comédia"
}

### delete gender
DELETE http://localhost:3000/genders/UCajXb5nx5BokOWeZzti_
